baseURL = 'https://www.tifrueh.ch/'
languageCode = 'en-GB'
title = 'Timo Früh'
copyright = 'All work is licensed under CC BY-SA 4.0, unless stated otherwise'
defaultContentLanguage = 'en'
pluralizeListTitles = false
disableKinds = [ 'taxonomy', 'term' ]

[menus]
[[menus.main]]
    name = '/about'
    pageRef = '/about'
[[menus.main]]
    name = '/links'
    pageRef = '/links-and-blogroll'
